spring:
  application:
    name: kotodo
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
  datasource:
    url: jdbc:h2:mem:kotodo-H2;MODE=mysql;
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
blog:
  title: Blog
  banner:
    title: Warning
    content: The blog will be down tomorrow.
